name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run ESLint
        run: eslint . --ext .js
      - name: Run test cases
        run: yarn test